dirs:
  artifacts:
    js: "artifacts/js"
    css: "artifacts/css"
  build:
    js: "build/js"
    css: "build/css"

header: |
  /*!
   * Company Name
   * http://www.company-website.com
   *
   * <%= bundle.name %> <%= bundle.version %>
   * <%= bundle[section-name].md5 %>
   */

tasks:

  build:
    options:
      js: true # calls requirejs, browserify, concat, or/and jsmin tasks if they are defined for bundle.
      css: true # calls preprocessor task first if defined for bundle.

  clean:
    options:
      force: true
      nowrite: false

  compass:
    options:

  cssc:
    options:

  cssconcat: ""
  csslint:
    options:

  cssmin: ""

  deploy: # If there is a key for a key in deploy in dirs.artifacts then that path is used for deployment instead.
    options:
      js: true
      css: true
      fonts: true
      images: true

  documentjs: ""

  documentcss: ""

  fixmyjs:
    options:

  jasmine:
    options:

  jsbeautify: ""

  jsbeautifier:
    options:

  jshint:
    options:

#  jslint: ""
#  jsmin: ""
#  prompt: ""
#  templates: ""
#  requirejs: ""
#  browserify: ""
#  watch: ""

  uglify:
    options:

  mustache:
    options:
