browserify:
  constructorLocation: ./bundle/task-proxies/BrowserifyProxy
  dependencies: browserify
  helpInfo: ""

build:
  constructorLocation: ./bundle/task-proxies/BuildProxy
  helpInfo: ""

clean:
  constructorLocation: ./bundle/task-proxies/CleanProxy
  dependencies: del
  helpInfo: ""

compass:
  constructorLocation: ./bundle/task-proxies/CompassProxy
  helpInfo: ""

concat:
  constructorLocation: ./bundle/task-proxies/ConcatProxy
  dependencies:
    - gulp-concat
    - gulp-uglify
  helpInfo: ""

csslint:
  constructorLocation: ./bundle/task-proxies/CssLintProxy
  helpInfo: ""

deploy:
  constructorLocation: ./bundle/task-proxies/DeployProxy
  helpInfo: ""

gulpfile:
  constructorLocation: ./bundle/task-proxies/GulpFileProxy
  helpInfo: ""

jshint:
  constructorLocation: ./bundle/task-proxies/JsHintProxy
  helpInfo: ""

htmllint:
  constructorLocation: ./bundle/task-proxies/HtmlLintProxy
  helpInfo: ""

minify:
  constructorLocation: ./bundle/task-proxies/MinifyProxy
  helpInfo: ""

requirejs:
  constructorLocation: ./bundle/task-proxies/RequireJsProxy
  helpInfo: ""

watch:
  constructorLocation: ./bundle/task-proxies/WatchProxy
  helpInfo: ""

wranglerfile:
  constructorLocation: ./bundle/task-proxies/WranglerFileProxy
  helpInfo: ""

