# File: default.bundle-template.yaml
# Description:  Sane recommended customizable tasks per bundle file.  The options and tasks that have
# been ommitted from this file are better off being configured globally (bundle.wrangler.config*)
# since they haven't been developed on a per bundle basis (yet).

# Browserify Defaults
# {Object}
browserify: null

# Compass task
compass: null

  # Compass project root (used to `cd` into to run
  #   `compass compile` and `compass watch` as sub processes)
  # {String}
  #compassProjectRoot: null # ./config.rb home

# Copy task
copy: null

  # Files to copy (key => value hash)
  # {Object}
  #files: null

# Clean task
clean: null

  # Files to clean
  # {Array}
  #files: null

# Deploy Task
deploy: null

  # Other files to be deployed.
  # Hash of file type keys with values of type {Array}.
  # {Object}
  #otherFiles: null

# Jasmin config
jasmine: null

  # Tests directory or array of files (test files)
  # {String|Array}
  #files: null

  # Jasmine options
  # {Object}
  #options: null

# Mocha config
mocha: null

  # Tests directory or array of files (test files)
  # {String|Array}
  #files: null

  # Mocha options
  # {Object}
  #options: null

# RequireJs config
# {Object}
requirejs: null
  #options: {}

# Watch Task Defaults
watch: null

  # Other files to watch.
  # {Array}
  #otherFiles: null
