clean: task-proxies/CleanProxy.js
compass: task-proxies/CompassProxy.js
concat: task-proxies/Concat.js
cssc: task-proxies/CssCProxy.js
csslint: task-proxies/CssLintProxy.js
cssmin: task-proxies/CssMinProxy.js
deploy: task-proxies/DeployProxy.js
documentjs: task-proxies/DocumentJsProxy.js
fixmyjs: task-proxies/FixMyJsProxy.js
gulpfile: taks-proxies/GulpFileProxy.js
jsbeautify: task-proxies/JsBeautifyProxy.js
jslint: task-proxies/JsLintProxy.js
uglify: task-proxies/UglifyProxy.js
templates: task-proxies/TemplatesProxy.js
prompt: task-proxies/PromptProxy.js
umd: task-proxies/UmdProxy.js
watch: task-proxies/WatchProxy.js
wranglerfile: taks-proxies/WranglerFileProxy.js
