all:
  constructorLocation: ./bundle/task-proxies/AllTasksProxy
  helpInfo: ""

browserify:
  constructorLocation: ./bundle/task-proxies/BrowserifyProxy
  helpInfo: ""

build:
  constructorLocation: ./bundle/task-proxies/BuildProxy
  helpInfo: ""

clean:
  constructorLocation: ./bundle/task-proxies/CleanProxy
  helpInfo: ""

compass:
  constructorLocation: ./bundle/task-proxies/CompassProxy
  helpInfo: ""

concat:
  constructorLocation: ./bundle/task-proxies/ConcatProxy
  helpInfo: ""

copy:
  constructorLocation: ./bundle/task-proxies/CopyProxy
  helpInfo: ""

csslint:
  constructorLocation: ./bundle/task-proxies/CssLintProxy
  helpInfo: ""

deploy:
  constructorLocation: ./bundle/task-proxies/DeployProxy
  helpInfo: ""

jshint:
  constructorLocation: ./bundle/task-proxies/JsHintProxy
  helpInfo: ""

minify:
  constructorLocation: ./bundle/task-proxies/MinifyProxy
  helpInfo: ""

requirejs:
  constructorLocation: ./bundle/task-proxies/RequireJsProxy
  helpInfo: ""

watch:
  constructorLocation: ./bundle/task-proxies/WatchProxy
  helpInfo: ""

config:
  constructorLocation: ./task-proxies/ConfigProxy
  helpInfo: ""

"bundle-config":
  constructorLocation: ./task-proxies/BundleConfigProxy
  helpInfo: ""

"deploy-config":
  constructorLocation: ./task-proxies/DeployConfigProxy
  helpInfo: ""

mocha:
  constructorLocation: ./bundle/task-proxies/MochaProxy
  helpInfo: ""

jasmine:
  constructorLocation: ./bundle/task-proxies/JasmineProxy
  helpInfo: ""
